### ISSUE TITLE
로고 디자인 작업하기

### ISSUE THREAD

**Issue by ggstargame45** [kookmin-sw/capstone-2024-19#44]

**Comment by ggstargame45** [comment]
![image](https://github.com/kookmin-sw/capstone-2024-19/assets/48516380/d9f73ee7-5163-483f-a720-12f1dd979358)

**Comment by ggstargame45** [comment]
![image](https://github.com/kookmin-sw/capstone-2024-19/assets/48516380/2c099e8b-0b48-4f23-8082-f881f2db142d)

**Comment by ggstargame45** [comment]
test

**Comment by Misun-k** [comment]
![4](https://github.com/kookmin-sw/capstone-2024-19/assets/55122068/c61221e5-9acc-4ad2-b076-651a5ebb523b)

**Comment by Misun-k** [comment]
![Uploading 3.png…]()

**Comment by Misun-k** [comment]
![Uploading 1.png…]()

**Comment by ggstargame45** [comment]
![image](https://github.com/kookmin-sw/capstone-2024-19/assets/48516380/e3ea97e7-3694-4fb1-a174-cb352d1c44ab)
