### ISSUE TITLE
[CHORE] 회의 3/29(금)

### ISSUE THREAD

**Issue by dbtkdfhr** [kookmin-sw/capstone-2024-19#60]
## 📝 업무 상세
1. 주간 스크럼
2. 중간보고서 작성
3. 마법사 기능 시연
4. 발표자 선정
5. 프론트 인원 중간보고서 이후 개발 할당

## 🏗️ 작업 상세
 - [ ] 깃허브 리드미 작성
 - [ ] 발표자료 작성
 - [ ] 프론트 디렉토리 분류 수정
 - [ ] 백엔드 멘토 질문사항 선정

## 👀 ***참고사항***

**Comment by minseokey** [comment]
@Misun-k 백엔드 맨토 질문사항 설정을 따로 이슈로 빼신 이유가 있으신가요?

**Comment by Misun-k** [comment]
엇 잘못 눌렸나봅니다
